#端口号
server:
  port: 8763

#项目名称
spring:
  application:
    name: eureka002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    register-with-eureka: false
    fetch-registry: false #设为false，不向自己注册，表示是服务端